# main text of home
name: Davor Ljubenkov
bio: Data Science ~ IT Management ~ GameDev

# twitter summary info
description: Davor Ljubenkov personal website

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile3.jpg

#markdown: kramdown
#highlighter: rouge

# If you want to include your resume, set to true
# and specify source (external or local).

resume: true
resume-external: true
resume-url: http://dljubenk.github.io/assets/Resume.pdf
#resume-url: https://docs.google.com/viewer?url=https://github.com/dljubenk/dljubenk.github.io/raw/master/assets/Resume.pdf

#https://www.slideshare.net/slideshow/embed_code/key/tSjWGgQ41DjFXO

url: http://dljubenk.github.io
# your url: http://USERNAME.github.io

use_logo: true
logo: http://dljubenk.github.io/assets/images/webicon2.png
avatar: http://dljubenk.github.io/assets/images/webicon2.png
logo_url: http://dljubenk.github.io/assets/images/webicon2.png

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-179176319-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# COMMENTS
# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: dljubenk # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: dljubenk
twitter: dljubenk
# google: mygoogle
instagram: dljubenk
# pinterest: mypinterest
linkedin: dljubenk
youtube: user/DavorLjubenkov
# spotify: myspotify
github: dljubenk
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: dljubenk@gmail.com
#researchgate: "https://www.researchgate.net/profile/Davor_Ljubenkov"
#researchgate: Davor_Ljubenkov
#google-scholar: RD5Nn_8AAAAJ&hl

authors:
    dljubenk:
        name: Davor Ljubenkov
        bio: an EU-US based panda nomad. always trying to learn new tricks for the show of questionable quality. serenity guaranteed.
        external-image: false
        picture: assets/images/profile.jpg
        twitter: dljubenk
    #jamesfoster:
        #name: James Foster
        #bio: A Man who develops software with coffee
        #external-image: false
        #picture: assets/images/james.jpg
        #twitter: jamesfoster

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
# projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
